# Generated by Django 2.2.4 on 2019-08-22 13:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20190822_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='logged',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
